### ISSUE TITLE
SOOTHSAYER compatiblity issue with ATAK CIV ver 4.10

### ISSUE THREAD

**Issue by telehawk911** [Cloud-RF/SOOTHSAYER-ATAK-plugin#15]
Hi,
Someone can help to find the solution regarding the subject issue.
The currently available version of SOOTHSAYER 1.1.1 is not compatible with the latest ATAK CIV version 4.10.
Upon checking in the plugin, it says not compatible.
I need it to use it with CloudRF.

Appreciate your support.

Thanks

**Comment by FarrantAlex** [comment]
Only 4.8 is supported presently. 4.10 support is planned for January.

**Comment by FarrantAlex** [comment]
4.10 is now supported. Please see the releases section for an updated apk

**Comment by telehawk911** [comment]
Thank you so much for your response and for the quick solution.
I appreciate your support.

Have a wonderful week

**Comment by telehawk911** [comment]
By the way, could you please tell me if this plugin is available and can be used in WinTAK v4.1.0.231?
Thanks
